remote_theme: pmarsceill/just-the-docs
# color_scheme: "dark"

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
    "Just the Docs on GitHub":
      - "//github.com/pmarsceill/just-the-docs"
